### ISSUE TITLE
Google Calendar with private or public ICS link not showing any events

### ISSUE THREAD

**Issue by krabs-github** [pedrofuentes/stream-deck-ical#4]
Google Calendar with private or public ICS link not showing any events at all. Easiest example is the list of US holidays. ICS results pasted below:

Developer unresponsive

**Comment by tjluoma** [comment]
I have two iCloud calendars and tried both of their URLs which are in this format:

`webcal://p56-caldav.icloud.com/published/2/LongStringOfCharactersHere`

and both say "No Meetings Found".

**Comment by pedropombeiro** [comment]
Same here, the plugin seems to have stopped working for me recently.
